### ISSUE TITLE
Attribute mapping JSON parsing

### ISSUE THREAD

**Issue by alexashley** [wehkamp/atlassian-crowd-client#16]
If a Crowd attribute is a valid Javascript string, but invalid JSON (e.g., '0123' is interpreted as an octal number), the call to JSON.parse [here](https://github.com/wehkamp/atlassian-crowd-client/blob/master/src/models/attributes.js#L29) fails.

Is the parsing necessary? Seems like it should be left to the consumer to do any necessary conversions.  I'd be happy to do a PR to remove it

**Comment by ghengeveld** [comment]
Converting to and from JSON is provided for convenience, but indeed not strictly necessary or flexible. I wouldn't go so far as to remove the feature, but we can allow it to be overridden. I'll change it so it can be overridden, but still default to using JSON encoding because it makes sense in most cases.

FYI this repo has moved here: https://github.com/ghengeveld/atlassian-crowd-client

**Comment by ghengeveld** [comment]
Done in [v1.5.0](https://www.npmjs.com/package/atlassian-crowd-client).

You can either [configure the `attributesEncoder`/`attributesParser` globally](https://github.com/ghengeveld/atlassian-crowd-client/blob/master/test/helpers/settings-example.js) or pass a custom encode/decode function to the API methods directly.

**Comment by alexashley** [comment]
@ghengeveld Wow! Thanks for the quick response! I wasn't able to use the custom parser/encoder settings (it didn't seem like the `CrowdApi` constructor stored them anywhere, so they were always undefined), so I opened a [pr](https://github.com/ghengeveld/atlassian-crowd-client/pull/4)
